### ISSUE TITLE
Mac Download 404

### ISSUE THREAD

**Issue by elootoo** [shopgoodwill-bid-sniper/shopgoodwill-auction-sniper#15]
Clicking on the Mac download leads me to a 404 page

**Comment by bid-sniper** [comment]
Hi elootoo, 

We are currently working on the Mac version and will have it back up within the next couple weeks...

**Comment by bid-sniper** [comment]
Hi, we should have the Mac version of the Auction Sniper up by this week...

**Comment by bid-sniper** [comment]
Great news, the Mac version of the ShopGoodwill auction sniper is released, but it is out of date but the old version still works fine too:

https://apps.apple.com/us/app/snipeable/id1613013930

**Comment by shopgoodwill-bid-sniper** [comment]
HI Everyone, we have released the Mac version of the ShopGoodwill sniper here:

https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper
