### ISSUE TITLE
**Urgent** Sniper tool keeps prompting me to buy another license

### ISSUE THREAD

**Issue by merchantmogul** [shopgoodwill-bid-sniper/shopgoodwill-auction-sniper#25]
Hi, 
I have been using your sniper goodwill tool for a month or so and it's been great.
However, today when I opened the tool and tried to bid with it it keeps prompting me to buy another license. see screenshot below.
but I already purchased a 6 month license.
Can someone please help me ASAP? i'm trying to make some bids on goodwill in the next hour before the bid closes.

![image](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/88c97833-457e-41c7-8fd6-dd0a0c907b0d)
![Screenshot 2024-03-23 200024](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/0458b5db-8505-4d17-9065-699460619ac4)

Thanks
Brad

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Brad,

We recently changed the name of the app which is what is causing the license issue, please go ahead and purchase the license again and we will refund it promptly!

Best regards,
Customer Service

**Comment by merchantmogul** [comment]
Ok. is that what is causing this error to pop up now when I launch the
sniper tool?

[image: image.png]

**Comment by merchantmogul** [comment]
![image](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/c809d9f4-098f-444b-9750-c4417f8ab262)

**Comment by merchantmogul** [comment]
Ok. I just paid again for another 6 months.

Can you please refund me asap please?

Thanks!
Brad

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Brad, your payment has been cancelled and refunded now... in regards to the error message, when does it occur, is it when you click something specifically and does it occur consistently or intermittently? Please let us know that information and we will look into it...

**Comment by merchantmogul** [comment]
Hi, the tool still is not working. when I enter my bid and click the button to add the bit, it just says "loading" and never changes and it get this pop up error everytime. Even when I closed everything and opened the app again. See attached screen shot.

Can you please help me? Thanks
![error message](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/2943fd29-64bf-402b-8ba3-cd720aac15ed)

**Comment by merchantmogul** [comment]
when I click Ok I get more information on the error. see attached.
![error 2](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/21d4208c-e2fe-4aa3-bc97-4c58a9c4c9a5)

**Comment by merchantmogul** [comment]
When I keep clicking on the "OK" butten eventually it shows "loading" status on my bid. But I don't have confidense it's going to fire off tonight.

![image](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/54a322c2-b78b-48e3-9331-7fd6ae18bdda)

**Comment by merchantmogul** [comment]
and when I now go to click on another item to bid that error pop up keeps popping up everywhere I try to go. something is definitely broken.
