### ISSUE TITLE
New Error Popup on Auction Sniper Tool

### ISSUE THREAD

**Issue by merchantmogul** [shopgoodwill-bid-sniper/shopgoodwill-auction-sniper#26]
Hi, the tool still is not working. when I enter my bid and click the button to add the bit, it just says "loading" and never changes and it get this pop up error everytime. Even when I closed everything and opened the app again. See attached screen shot.

Can you please help me? Thanks
error message

![image](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/d0458aef-8509-417a-9ea2-4176d2cd14cd)

when I click Ok I get more information on the error. see attached.

![image](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/da95668f-443d-451d-98a6-7521cafaae81)

When I keep clicking on the "OK" button eventually it shows "loaded" status on my bid. But I don't have confidence it's going to fire off tonight.

![image](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/160200040/95a2e628-2fa5-433c-996a-7d88dd141f7f)

and when I now go to click on another item to bid that error pop up keeps popping up everywhere I try to go. something is definitely broken.

**Comment by shopgoodwill-bid-sniper** [comment]
Yes, it sounds like something is not working well, can you please go to the App Store app and update it to the latest version here:

https://apps.microsoft.com/detail/9nlhnknjm66j

Please let us know if the problem still persists after you update...
