### ISSUE TITLE
Missed snipes and doesn't work when computer is sleeping

### ISSUE THREAD

**Issue by katiestewart23** [shopgoodwill-bid-sniper/shopgoodwill-auction-sniper#27]
For reference, I'm running Windows 11 home and bid sniper version 24.3.2518.0.

It doesn't appear that bid sniper will work without the computer being open and awake. For starters, is that how it's supposed to function?

If I close my laptop and sleep the computer, bid sniper won't submit bids. Recently, even when awake it seems like it isn't firing every time and I'm losing auctions at prices below my loaded bids.

Are there settings I should adjust or a new version to install that fixes this?

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Katie,

Please ensure your laptop lid is open and your computer is not sleeping during the bidding process as this will interrupt the automated bid... please also ensure you are using the latest version by going here:

[https://apps.microsoft.com/detail/9nlhnknjm66j](https://apps.microsoft.com/detail/9nlhnknjm66j)

Aside from that, you can also increase the snipe delay timer in the top menu of the main window however please note that increasing the delay may allow someone else to outbid your snipe so keep that in mind when increasing that timer.

I hope that answers your questions, please let us know if we can be of further assistance!

Best Regards,
Customer Service

**Comment by katiestewart23** [comment]
Hello, can you please help me with this item? I had my sleep settings off, computer on, lid open, etc. All the things you listed and my maximum was still set way higher than the closing bid. Are you able to look and see how I missed this one? [Shop194381612](https://shopgoodwill.com/item/194381612)

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Katie, it all runs on your own computer so we can't really tell why it didn't run in your particular case at that particular time, but if you turned off your computers sleep settings and it still didn't go off on time try increasing your snipe delay in the top main menu settings to 10 seconds and see if that helps?

Please let us know if that doesn't work and we will work with you ...

**Comment by katiestewart23** [comment]
I have updated my app and changed my settings to 10 seconds. I am still
getting this error. Any insight?
[image: IMG_0962.jpg]

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Katie,

The image in your comment is not displaying properly can you please post it again?

**Comment by katiestewart23** [comment]
Please see attached and let me know if it uploaded this time. I again missed out on several items last night and I'm not sure why. This error pops up every time I open my app. Then I log out and log back in and it still won't work with snipes I have set up. I checked the closed items this morning and they closed way lower than what I had set. I have uninstalled the app, reinstalled, left my lid open, changed the time, etc. Everything you have suggested and it still isn't working. Please advise as I am paying for this app and it doesn't seem to be working correctly?

![IMG_0962 (1)](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/165221442/3f67b37a-e42a-46aa-a74f-148c952db8a1)

**Comment by katiestewart23** [comment]
Hello, I also received this error tonight.
![Screenshot 2024-04-01 193537](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/165221442/b364d166-b632-4a6c-bb2b-23bbd51ee6b0)

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Katie, 

What action are you taking when this error pops up so that we can reproduce it?

**Comment by katiestewart23** [comment]
Hi, it honestly just happens randomly. Sometimes when I'm not even using the app and then I'll open it up and the error is there.

Please see attached screen shots. You will see I had all my snipes loaded and then when it comes time to bid, the app freezes up and won't load. Then I lose the auction even though my price is higher. I'm extremely frustrated with this. I won one just a few minutes before this one, then I plugged my charger in and walked away (leaving my lid open, screen on, sleep settings off) and I lost all of these. 

In the meantime, can I have a credit or a refund? It's clearly not working as intended and I'm really not sure why. Any suggestions? Thanks!

![image (49)](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/165221442/dfda9b44-eac4-4368-b503-d9e0bd6e7a16)



![image (48)](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/165221442/cc22cd17-a6e5-4dc6-a33e-e385535f13a4)
![Screenshot 2024-04-02 081951](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/165221442/95c2e41b-e599-45ee-8c97-cd6db9aa2e67)

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Katie,

Yes, we will give you a refund in the meanwhile while we resolve that error what date and amount was your payment?

**Comment by katiestewart23** [comment]
I'll have to find it. Are you able to tell me what it would show on the CC as?

**Comment by shopgoodwill-bid-sniper** [comment]
I found that you paid $24.99, we will refund this back and you should receive it within the next few days...

**Comment by katiestewart23** [comment]
Thank you! Did you receive the screen shots I sent earlier as well?

**Comment by shopgoodwill-bid-sniper** [comment]
Yes, we will look into that error and fix it but it will take up to a couple weeks to release new fix!

**Comment by shopgoodwill-bid-sniper** [comment]
You're very welcome, we'll let you know when the fix is released here...

**Comment by katiestewart23** [comment]
Hello. Wanted to send the error again and what happened. I had 5 snipes set up. My first one went off fine. Then when I refreshed my app, it did the pink admin error I sent above and the attached error. This is what happened the other night too. My first snipe went off, then after that, my app froze up and wouldn't load anything or snipe any others after the first. Just thought this may help.
![IMG_1107](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/165221442/a04f4cd2-4e97-41be-8078-9c98419fef38)

**Comment by shopgoodwill-bid-sniper** [comment]
Thank you for the screenshot Katie, we will look into this error and reply back to you here shortly...

**Comment by Bubbadogg1** [comment]
I am having the same issue. The only snipe that worked was the 1 I did before buying the subscription. Now I get error codes everytime I open it. And my snipes are not going through even though I have them set to 20 secs.  I only get the LOST sound well after the auction has ended. Also, when I try to open the item page through the app, I only get a PLEASE WAIT loading screen and it never finishes loading.
![Screenshot_3](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/166778344/f4dafef0-49e0-4e73-8b1a-b2d1ff32dc95)
The app has not worked properly since I payed for it. I just downloaded a few days ago and even redownloaded just to make sure I have the current version.
Windows 11
BTW, When I load in a new auction by using the ID directly, It takes a few minutes for it show LOADED.

**Comment by Bubbadogg1** [comment]
![Screenshot_4](https://github.com/shopgoodwill-bid-sniper/shopgoodwill-auction-sniper/assets/166778344/3cd74ee9-3175-458f-bb9b-0461b986ce7c)

**Comment by shopgoodwill-bid-sniper** [comment]
Hi we are currently working on this issue and should have a fix released within the next few weeks...

**Comment by Bubbadogg1** [comment]
Is there any chance of getting a refund or credit since I'm paying for the monthly subscription?

**Comment by shopgoodwill-bid-sniper** [comment]
Hi bubbadog1, yes, we can offer you a refund, what is your name and date of your payment?

**Comment by Bubbadogg1** [comment]
Wayne - April 9

**Comment by shopgoodwill-bid-sniper** [comment]
Hi bubbadog1,

We have issued a refund to Wayne for $9.99 on the date of April 9th, you should see the refund in a few days!

**Comment by Bubbadogg1** [comment]
Thank you. Please keep me updated as to when this gets fixed. I would still like to subscribe and use.

**Comment by shopgoodwill-bid-sniper** [comment]
Ok will do, it will take a couple weeks...

**Comment by katiestewart23** [comment]
> I found that you paid $24.99, we will refund this back and you should receive it within the next few days...

are you able to see if my refund was issued? I dont see it hitting my cc.

**Comment by katiestewart23** [comment]
any update on this? mine is still not working --
[image: image.png]
