### ISSUE TITLE
not bidding

### ISSUE THREAD

**Issue by jimmothy86** [shopgoodwill-bid-sniper/shopgoodwill-auction-sniper#29]
I entered items into the bid sniper along with my highest bid, and it loads it, says its loaded, identifies the correct item, and then just plays the "sorry you lost" sound without even placing a bid, it worked for the first auction, earlier today, and then the next 2 failed to do anything but let me know I lost.

**Comment by shopgoodwill-bid-sniper** [comment]
Hi Jimmyothy,

Try increasing the snipe timing from the top menu at the top to 10 seconds instead of the default 5 seconds because shopgoodwills website is slow...
