### ISSUE TITLE
6 months paid 

### ISSUE THREAD

**Issue by jake35th** [shopgoodwill-bid-sniper/shopgoodwill-auction-sniper#31]
I paid for 6 months subscription.  I can only load one item.  When I try and load more I get prompted to pay again.
I was not winning auctions and un-installed the app and re installed it.  Not sure if this is this issue.  Please advise.

**Comment by shopgoodwill-bid-sniper** [comment]
If you uninstall and reinstall it uninstalls the license too.

**Comment by jake35th** [comment]
How about a refund?

**Comment by jake35th** [comment]
I would like to keep paying to use the app but seems silly to pay for something I can;t use.

**Comment by jake35th** [comment]
Not sure if I respond here or on the forum.  How about a refund?  I would like to keep paying to use the app but not if I have have to pay again.  


Jake
