### ISSUE TITLE
Refund 

### ISSUE THREAD

**Issue by jake35th** [shopgoodwill-bid-sniper/shopgoodwill-auction-sniper#32]
How about a refund?  I would like to keep using the app but not if I have have to pay again.

**Comment by shopgoodwill-bid-sniper** [comment]
Yes, we have issued you a refund so you can go ahead and purchase it again now...

**Comment by jake35th** [comment]
Cool.  Thanks for the update.

**Comment by shopgoodwill-bid-sniper** [comment]
You're welcome, please let us know if we can be of further assistance!

Customer Service

**Comment by jake35th** [comment]
Just wanted to follow up.  Did you initiate a refund yet?  I have not seen anything on my end yet.

Thanks 

Jake
